server:
  port: 8083

spring:
  application:
    name: aml-screening

  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

aml:
  queues:
    screening-tx: AML.SCREENING.TX
